- platform: mqtt
  name: "Living Room Temp"
  state_topic: "home/sonoff/living_room/1/temp"
  qos: 1
  # Set unit_of_measurement to "°C" or "°F" to match the temperature scale chosen in config_sc.h
  unit_of_measurement: "°C"
  value_template: "{{ value_json.Temp | round(1) }}"

- platform: mqtt
  name: "Living Room Humidity"
  state_topic: "home/sonoff/living_room/1/temp"
  qos: 1
  unit_of_measurement: "%"
  value_template: "{{ value_json.Humidity | round(1) }}"

- platform: mqtt
  state_topic: "home/sonoff/living_room/1/temp"
  name: "Living Room Real Feel"
  qos: 1
  # Set unit_of_measurement to "°C" or "°F" to match the temperature scale chosen in config_sc.h
  unit_of_measurement: "°C"
  value_template: "{{ value_json.HeatIndex | round(1) }}"
  